blog/urls.py
from django.urls import path

from . import views
from blog.views import BlogListView

app_name="blog"


urlpatterns = [
    path('detail/<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('', BlogListView.as_view(), name='blog_list'),
]

home/urls.py
from django.urls import path
# yazdigimiz functions imporr edirk
from .views import  HomeListView
app_name="home"


urlpatterns = [
    path('', HomeListView.as_view(), name='index'),
   
]

mydjangoproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
      
    path('jet/', include('jet.urls', 'jet')),  
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
   


    # path('checkout/', include('order.urls', namespace="checkout")),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)




from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns += i18n_patterns(
    
    path('about/',include("about.urls",namespace="about"),),
    path('',include("product.urls",namespace="product"),),
    path('',include("shop.urls",namespace="shop"),),
    path('blog/',include("blog.urls",namespace="blog"),),
    path('',include("home.urls",namespace="home"),),
    path('contact/',include("contact.urls",namespace="email"),),
    path('contact/',include("contact.urls",namespace="thanks"),),
    path('account/',include("account.urls",namespace="register"),),
    path('account/',include("account.urls",namespace="login"),),
    path('contact/', include('contact.urls', namespace="feedback")),
    path('social-auth/', include('social_django.urls', namespace="social")),


    # path('orders/', include('orders.urls', namespace='orders')),
    
)

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('item/<slug:slug>/', views.product_detail, name='product_detail'),
    path('list/', views.list , name='product_list'),
    path('item/<slug:category_slug>/', views.category_list, name='category_list'),
]

home/models.py
from django.db import models




class Home(models.Model):
    image = models.ImageField(upload_to="media/")
    header=models.CharField(max_length=100, null=True,blank=True)
    desc = models.CharField(max_length=100, null=True, blank=True)
    price = models.CharField(max_length=100, null=True)


    class Meta: 
        verbose_name_plural = "Home"
     
    
    def __str__(self):
        return self.header

class Slider(models.Model):
    image = models.ImageField(upload_to="media/")
    header=models.CharField(max_length=100,blank=True,null=True)
    desc = models.CharField(max_length=100,blank=True,null=True)
    title= models.CharField(max_length=100, blank=True)


    def __str__(self):
        return self.header

home/views.py
from django.shortcuts import render
from . models import Home,Slider
from django.views.generic import ListView





class HomeListView(ListView):
    model = Home
    template_name = 'index.html'
    paginate_by = 4
    context_object_name='products'
    queryset = Home.objects.all()
  
    # multi models one list wiew
    def get_context_data(self,**kwargs):
        context=super(HomeListView,self).get_context_data(**kwargs)
        context['sliders']=Slider.objects.all()
        return context

home/templates/base.html
{% load static  %}
{% load i18n %}
{% block css  %} 



<!DOCTYPE html>
<html lang="en">
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet" />
<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Playfair+Display:400,700,900' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="{% static 'css/animate.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
<link rel="stylesheet" href="{% static 'css/ionicons.css' %}">
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="{% static 'css/responsive.css' %}">
<link rel="stylesheet" href="{% static 'css/settings-ie8.css' %}">  
<link rel="stylesheet" href="{% static 'css/settings.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  

{% include 'includes/navbar.html' %}


{% block content  %}

{% endblock  %}

<section class="small-about padding-top-150 padding-bottom-150">
  <div class="container"> 
    
    <!-- Main Heading -->
    <div class="heading text-center">
      <h4>about PAVSHOP</h4>
      <p>Phasellus lacinia fermentum bibendum. Interdum et malesuada fames ac ante ipsumien lacus, eu posuere odio luctus non. Nulla lacinia,
        eros vel fermentum consectetur, risus purus tempc, et iaculis odio dolor in ex. </p>
    </div>
    
    <!-- Social Icons -->
    <ul class="social_icons" >
      <li><a href="#." style="font-size: 31px;"><i class="fa-brands fa-facebook-f"></i></a></li>
      <li><a href="#." style="font-size: 31px;"><i class="fab fa-instagram"></i></a></li>
      <li><a href="#." style="font-size: 31px;"><i class="fab fa-telegram"></i></a></li>
      <li><a href="#." style="font-size: 31px;"><i class="fab fa-twitter"></i></a></li>
    </ul>
  </div>
</section>

<section class="news-letter padding-top-150 padding-bottom-150">
    <div class="container">
      <div class="heading light-head text-center margin-bottom-30">
        <h4>NEWSLETTER</h4>
        <span>Phasellus lacinia fermentum bibendum. Interdum et malesuada fames ac ante ipsumien lacus, eu posuere odi </span> </div>
      <form>
        <input type="email" placeholder="Enter your email address" required>
        <button type="submit">SEND ME</button>
      </form>
    </div>
  </section>

  
{% include 'includes/footer.html' %}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
<script src="{% static 'js/modernizr.js' %}"></script>
<script type='text/javascript' src='http://maps.google.com/maps/api/js?sensor=false'></script> 
<script src="{% static 'js/bootsrap.min.js' %}"></script>
<script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
<script src="{% static 'js/jquery.fatNav.min.js' %}"></script>
<script src="{% static 'js/jquery.lighter.js' %}"></script>
<script src="{% static 'js/jquery.themepunch.enablelog.js' %}"></script>
<script src="{% static 'js/jquery.themepunch.revolution.js' %}"></script>
<script src="{% static 'js/jquery.tp.min.js' %}"></script>
<script src="{% static 'js/jquery.tp.t.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/own-menu.js' %}"></script>
<script src="{% static 'js/smooth-scroll.js' %}"></script>
{% endblock css %}
</body>
</html>

home/templates/index.html
{% extends 'base.html' %}
{% load static %}
<!-- multi language -->
{% load i18n %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="M_Adnan">

<div id="loader">
  <div class="position-center-center">
    <div class="ldr"></div>
  </div>
</div>

<!-- Wrap -->
<div id="wrap"> 
  
  <!--======= HOME MAIN SLIDER =========-->
  <section class="home-slider"> 
  
    <!-- SLIDE Start -->
    <div class="tp-banner-container">
      <div class="tp-banner">
        <ul>  
          {% for slider in sliders %}
          <!-- SLIDE  -->
          <li data-transition="random" data-slotamount="7" data-masterspeed="300"  data-saveperformance="off" > 

  
            <!-- MAIN IMAGE --> 
            <img src="{{ slider.image.url  }}"  alt="slider"  data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">     
          
            <!-- LAYERS --> 
            <!-- LAYER NR. 1 -->
            <div class="tp-caption font-playfair sfb tp-resizeme" 
                data-x="left" data-hoffset="0" 
                data-y="center" data-voffset="-200" 
                data-speed="800" 
                data-start="500" 
                data-easing="Power3.easeInOut" 
                data-splitin="none" 
                data-splitout="none" 
                data-elementdelay="0.1" 
                data-endelementdelay="0.1" 
                data-endspeed="300" 
                style="z-index: 7; font-size:18px; color:#fff; max-width: auto; max-height: auto; white-space: nowrap;">{{slider.header}}</div>
            <!-- LAYER NR. 2 -->
            <div class="tp-caption sfl font-extra-bold tp-resizeme" 
                data-x="left" data-hoffset="0" 
                data-y="center" data-voffset="-120" 
                data-speed="800" 
                data-start="800" 
                data-easing="Power3.easeInOut" 
                data-splitin="none" 
                data-splitout="none" 
                data-elementdelay="0.07" 
                data-endelementdelay="0.1" 
                data-endspeed="300" 
                style="z-index: 6; font-size:80px; color:#fff;; text-transform:uppercase; white-space: nowrap;"><small class="font-regular">{{slider.desc}}</small> </div>
            <!-- LAYER NR. 2 -->
            <div class="tp-caption sfr font-extra-bold tp-resizeme" 
                data-x="left" data-hoffset="0" 
                data-y="center" data-voffset="0" 
                data-speed="800" 
                data-start="800" 
                data-easing="Power3.easeInOut" 
                data-splitin="chars" 
                data-splitout="none" 
                data-elementdelay="0.07" 
                data-endelementdelay="0.1" 
                data-endspeed="300" 
                style="z-index: 6; font-size:120px; color:#fff; text-transform:uppercase; white-space: nowrap;">
               </div> 
              
            <!-- LAYER NR. 2 -->
            <div class="tp-caption sfr font-extra-bold tp-resizeme" 
                data-x="left" data-hoffset="0" 
                data-y="center" data-voffset="110" 
                data-speed="800" 
                data-start="1300" 
                data-easing="Power3.easeInOut" 
                data-splitin="chars" 
                data-splitout="none" 
                data-elementdelay="0.07" 
                data-endelementdelay="0.1" 
                data-endspeed="300" 
                style="z-index: 6; font-size:120px; color:#fff; text-transform:uppercase; white-space: nowrap;">{{slider.title}} </div>
            <!-- LAYER NR. 4 -->
            <div class="tp-caption lfb tp-resizeme" 
                data-x="left" data-hoffset="0" 
                data-y="center" data-voffset="240" 
                data-speed="800" 
                data-start="2200" 
                data-easing="Power3.easeInOut" 
                data-elementdelay="0.1" 
                data-endelementdelay="0.1" 
                data-endspeed="300" 
                data-scrolloffset="0"
                style="z-index: 8;"><a href="{%  url 'product:product_list'  %}" class="btn">SHOP NOW</a> </div>
          </li>
            {% endfor %}
    
        </ul>
      </div>
    </div>
  </section>
  
  <!-- Content -->
  <div id="content"> 
    
    <!-- New Arrival -->
    <section class="padding-top-100 padding-bottom-100">
      <div class="container"> 
        
        <!-- Main Heading -->
        <div class="heading text-center">
          <h4>new arrival</h4>
          <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec faucibus maximus vehicula. 
          Sed feugiat, tellus vel tristique posuere, diam</span> </div>
      </div>
      
      <!-- New Arrival -->
      <div class="arrival-block single-img-demos"> 
        
        {% for product in products %}
        <!-- Item -->
        <div class="item"> 
          <!-- Images --> 
          <img class="img-1" src="{{ product.image.url  }}" alt=""> 
          <!-- Overlay  -->
          <div class="overlay"> 
            <!-- Price --> 
            <span class="price"> {{product.price}} <small>$</small>   </span>
            <div class="position-center-center"> <a href="images/item-img-1-1.jpg" data-lighter><i class="fas fa-search"></i></a> </div>
          </div>
          <!-- Item Name -->
          <div class="item-name"> <a href="#.">{{product.header}}</a>
            <p>{{product.desc}}</p>
          </div>
        </div>
        
     {%  endfor  %}  
     

    </section>
    
    <!-- Popular Products -->
    <section class="padding-top-50 padding-bottom-150">
      <div class="container"> 
        
        <!-- Main Heading -->
        <div class="heading text-center">
          <h4>popular products</h4>
          <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec faucibus maximus vehicula. 
          Sed feugiat, tellus vel tristique posuere, diam</span> </div>
        
        <!-- Popular Item Slide -->
        <div class="papular-block block-slide single-img-demos"> 
          
        
            {% for product in products  %}
          <!-- Item -->
          <div class="item"> 
            <!-- Item img -->
            <div class="item-img" style="height:175px; margin: 0 auto 30px auto;"> <img class="img-1" src="{{ product.image.url  }}" alt="" > 
              <!-- Overlay -->
              <div class="overlay">
                <div class="position-center-center">
                  <div class="inn"><a href="  {{ product.image.url  }}" data-lighter><i class="fas fa-search"></i></a> </i></a> <a href="#." ><i class="fas fa-heart"></i></a></div>
                </div>
              </div>
            </div>
            <!-- Item Name -->
            <div class="item-name"> <a href="#.">{{ product.header }}</a>
              <p> {{ product.desc }} </p>
            </div>
            <!-- Price --> 
            <span class="price"><small>{{ product.price  }} $ </small></span> </div>
          
          <!-- Item -->
       
{%  endfor  %}

      </div>
       
      <ul class="pagination justify-content-center mb-10 pb-2 pt-2 mt-8" style="display: flex;justify-content: center;float: none;">
        <li class="prev disabled">
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous" tabindex="-1" aria-disabled="true" style="margin: 0 5px;height: 33px;width: 33px;line-height: 31px;
            justify-content: center;align-items: center;font-size: 12px;border-radius: 0px !important;border: none;background: #2d3a4b;color: #fff;padding: 0px;text-align: center; font-size: 12px; cursor: pointer;"
            >
                <i class="w-icon-long-arrow-left"></i>Prev
            </a>
                <!-- <a href="?page=1"></a> -->

            {% endif %}
        </li>
        {% for page in page_obj.paginator.page_range %}
                    {% if page is page_obj.number %}
                        <li class="page-item active"><a class="page-link" style="margin: 0 5px;height: 33px;width: 33px;line-height: 31px;
                          justify-content: center;align-items: center;font-size: 12px;" href="#">{{page}}</a></li>
                    {% else %}
                        <li class="page-item"><a href="?page={{page}}" class='page-link' style="margin: 0 5px;height: 33px;width: 33px;line-height: 31px;
                          justify-content: center;align-items: center;font-size: 12px;">{{page}}</a></li>
                        <a href="?page={{ page_obj.paginator.num_pages }}" ></a>
                    {% endif %}
                {% endfor %}
        <li class="next">
            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" aria-label="Next" style="margin: 0 5px;height: 33px;width: 33px;line-height: 31px;
            justify-content: center;align-items: center;font-size: 12px;">
                Next<i class="w-icon-long-arrow-right"></i>
            </a>
            {% endif %}
        </li>
    </ul>

      

    </section>
    

  
  </div>
  

</div>

</body>
</html>
{% endblock %}