about/urls.py
from django.urls import path
# from .models import AboutTeam
from .views import about

app_name="about"


urlpatterns = [
    path('', about, name='about'),
]

account/urls.py
from django.urls import path,re_path,include
# yazdigimiz functions imporr edirk
from .views import register,activate,login,logout

app_name="account"


urlpatterns = [
    path('register/', register, name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,33})/$',activate, name='activate'),
    path('login/',login , name='login'),
    path('logout/',logout , name='logout'),
    
]

blog/urls.py
from django.urls import path

from . import views
from blog.views import BlogListView

app_name="blog"


urlpatterns = [
    path('detail/<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('', BlogListView.as_view(), name='blog_list'),
]

contact/urls.py
from django.urls import path
from .views import feedback

app_name="contact"

urlpatterns = [
    path('', feedback, name='feedback'),
 
]

home/urls.py
from django.urls import path
# yazdigimiz functions imporr edirk
from .views import  HomeListView
app_name="home"


urlpatterns = [
    path('', HomeListView.as_view(), name='index'),
   
]

mydjangoproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
      
    path('jet/', include('jet.urls', 'jet')),  
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
   


    # path('checkout/', include('order.urls', namespace="checkout")),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)




from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns += i18n_patterns(
    
    path('about/',include("about.urls",namespace="about"),),
    path('',include("product.urls",namespace="product"),),
    path('',include("shop.urls",namespace="shop"),),
    path('blog/',include("blog.urls",namespace="blog"),),
    path('',include("home.urls",namespace="home"),),
    path('contact/',include("contact.urls",namespace="email"),),
    path('contact/',include("contact.urls",namespace="thanks"),),
    path('account/',include("account.urls",namespace="register"),),
    path('account/',include("account.urls",namespace="login"),),
    path('contact/', include('contact.urls', namespace="feedback")),
    path('social-auth/', include('social_django.urls', namespace="social")),


    # path('orders/', include('orders.urls', namespace='orders')),
    
)

shop/urls.py
from django.urls import path
from .views import basket_summary, checkout,basket_add,basket_delete,basket_update

app_name = 'shop'

urlpatterns = [
    path('basket/', basket_summary, name='basket_summary'),
    path('add/', basket_add, name='basket_add'),
    path('checkout/', checkout, name='checkout'),
    path('delete/',basket_delete, name='basket_delete'),
    path('update/',basket_update, name='basket_update'),

    
    
]

home/models.py
from django.db import models




class Home(models.Model):
    image = models.ImageField(upload_to="media/")
    header=models.CharField(max_length=100, null=True,blank=True)
    desc = models.CharField(max_length=100, null=True, blank=True)
    price = models.CharField(max_length=100, null=True)


    class Meta: 
        verbose_name_plural = "Home"
     
    
    def __str__(self):
        return self.header

class Slider(models.Model):
    image = models.ImageField(upload_to="media/")
    header=models.CharField(max_length=100,blank=True,null=True)
    desc = models.CharField(max_length=100,blank=True,null=True)
    title= models.CharField(max_length=100, blank=True)


    def __str__(self):
        return self.header

home/views.py
from django.shortcuts import render
from . models import Home,Slider
from django.views.generic import ListView





class HomeListView(ListView):
    model = Home
    template_name = 'index.html'
    paginate_by = 4
    context_object_name='products'
    queryset = Home.objects.all()
  
    # multi models one list wiew
    def get_context_data(self,**kwargs):
        context=super(HomeListView,self).get_context_data(**kwargs)
        context['sliders']=Slider.objects.all()
        return context

home/templates/includes/footer.html
{% load static %}
  <footer>
    <div class="container"> 
      
      <!-- Location -->
      <div class="col-md-3">
        <div class="about-footer"> <img class="margin-bottom-30" src="{% static 'images/logo-foot.png' %}" alt="" >
          <p><i class="icon-call-end"></i> +994 055 555 55 65</p>
          <p><i class="icon-envelope"></i> info@PAVSHOP.com</p>
        </div>
      </div>
      
      <!-- HELPFUL LINKS -->
      <div class="col-md-3">
        <h6>HELPFUL LINKS</h6>
        <ul class="link">
          <li><a href="{% url 'product:product_list'  %}"> Products</a></li>
          <li><a href="{% url 'blog:blog_list'  %}"> Blog</a></li>
        </ul>
      </div>
      
      <!-- SHOP -->
      <div class="col-md-3">
        <h6>SHOP</h6>
        <ul class="link">
          <li><a href="{% url 'about:about'  %}"> About Us</a></li>
          <li><a href="{% url 'contact:feedback' %}"> Contact</a></li>

        </ul>
      </div>
      
      <!-- MY ACCOUNT -->
      <div class="col-md-3">
        <h6>MY ACCOUNT</h6>
        <ul class="link">
          <li><a href="{% url 'account:login'  %}"> Login</a></li>
          <li><a href="{%  url 'shop:basket_summary' %}"> My Cart</a></li>
          <li><a href="{% url 'shop:checkout' %}"> Checkout</a></li>
        </ul>
      </div>
      
      <!-- Rights -->
      <div class="rights">
        <p>©  2022 PAVSHOP All right reserved. </p>
        <div class="scroll"> <a href="#wrap" class="go-up"><i class="fas fa-arrow-up"></i></a> </div>
      </div>
    </div>
  </footer>  

home/templates/includes/navbar.html
{% load static %}
{% load i18n %}
<header>

  
<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Playfair+Display:400,700,900' rel='stylesheet' type='text/css'>
    <div class="sticky">
      <div class="container"> 
        
        <!-- Logo -->
        <div class="logo"> <a href="{% url 'home:index' %}"><img class="img-responsive" src="{% static 'images/logo.png' %}" alt="" ></a> </div>
        <nav class="navbar ownmenu testfornavbar" style="display: flex !important; justify-content: center !important;align-items: center !important; ">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-open-btn" aria-expanded="false"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"><i class="fa fa-navicon"></i></span> </button>
          </div>
          
           <!-- NAV -->
          <div class="collapse navbar-collapse" id="nav-open-btn">
            <ul class="nav">
              <li class="dropdown active"> <a href="{% url 'home:index' %}" class="dropdown-toggle" data-toggle="dropdown">Home</a>
              </li>
             

              <!-- <li class="dropdown"><a href=" " class="dropdown-toggle" data-toggle="dropdown">Store</a> -->
<!--               
              <li class="dropdown"> <a href="#." class="dropdown-toggle" data-toggle="dropdown">Pages</a> -->
            
                  <li> <a href="{% url 'product:product_list' %}">  Product </a> </li>
                  <li> <a href="{% url 'blog:blog_list' %}">Blog </a> </li>
            
              </li>
              <li> <a href="{% url 'about:about' %}">About </a> </li>
            
             
              <li> <a href="{% url 'contact:feedback' %}">Contact</a> </li>
            </ul>
          </div>
          
          {% if user.is_authenticated %}
          <a style="text-transform: uppercase;letter-spacing: 3px;font-size: 15px;margin-right: 9px;" href="{% url 'account:logout' %}">Logout</a>
          
          {% else %}
          <a style="text-transform: uppercase;letter-spacing: 3px;font-size: 15px;margin-right: 9px;" href="{% url 'account:login' %}">Login</a>
          {% endif %}
          <!-- Nav Right -->
          <div class="nav-right">    
              <!-- USER INFO -->
              <ul class="nav nav-pills navbar-right"">
                <li class="nav-item dropdown">
                   <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="{% url 'account:register'%}" role="button" aria-expanded="false"><i class="far fa-user"></i></a>
                  
            
                <div>


              <!-- USER BASKET -->

                  <li class="nav-item dropdown">
                   
                 
                    <a type="button" role="button" href="{% url "shop:basket_summary" %}">
                    

                    {% with total_qty=basket|length %}
                        <div id="basket-qty" class="d-inline-flex" style="padding: 1px 1px 1px 5px;position: absolute;
                        z-index: 3;background: #fde11f;border-radius: 20px;left: 42%;top: 0%;color: #746d6d;font-weight: 600;font-size: 15px;">
                            {% if total_qty > 0 %}
                                {{ total_qty }}
                            {% else %}
                                0
                            {% endif %}
                        </div>
                    {% endwith %} 

                    <i class="fa fa-shopping-basket"></i>
           
                </a>

                </li>


             

                <li class="dropdown"> <a href="javascript:void(0);" class="search-open"> <i class="fas fa-search"></i>  </a>
                  <div class="search-inside animated bounceInUp"> <i class="icon-close search-close"> <i class="fas fa-times"></i> </i>
                    <div class="position-center-center">
                      <div class="search">
                        <form>
                          <input type="search" placeholder="Search Shop">
                          <button type="submit"><i class="icon-check"></i></button>
                        </form>
                      </div>
                    </div>
                  </div>
                </li>


                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Language
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
        
                    {% for lang in languages %}
                      <li>
                      <a class="dropdown-item" href="/{{ lang.code }}/">
                          {{ lang.name_local }}
                      </a>
                      </li>
                    {% endfor %}
                  </ul>
                </li>

             </ul>
             
          </div>
        </nav>
      </div>
      
    </div>
  </header>

  