blog/urls.py
from django.urls import path

from . import views
from blog.views import BlogListView

app_name="blog"


urlpatterns = [
    path('detail/<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('', BlogListView.as_view(), name='blog_list'),
]

mydjangoproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
      
    path('jet/', include('jet.urls', 'jet')),  
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
   


    # path('checkout/', include('order.urls', namespace="checkout")),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)




from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns += i18n_patterns(
    
    path('about/',include("about.urls",namespace="about"),),
    path('',include("product.urls",namespace="product"),),
    path('',include("shop.urls",namespace="shop"),),
    path('blog/',include("blog.urls",namespace="blog"),),
    path('',include("home.urls",namespace="home"),),
    path('contact/',include("contact.urls",namespace="email"),),
    path('contact/',include("contact.urls",namespace="thanks"),),
    path('account/',include("account.urls",namespace="register"),),
    path('account/',include("account.urls",namespace="login"),),
    path('contact/', include('contact.urls', namespace="feedback")),
    path('social-auth/', include('social_django.urls', namespace="social")),


    # path('orders/', include('orders.urls', namespace='orders')),
    
)

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('item/<slug:slug>/', views.product_detail, name='product_detail'),
    path('list/', views.list , name='product_list'),
    path('item/<slug:category_slug>/', views.category_list, name='category_list'),
]

shop/urls.py
from django.urls import path
from .views import basket_summary, checkout,basket_add,basket_delete,basket_update

app_name = 'shop'

urlpatterns = [
    path('basket/', basket_summary, name='basket_summary'),
    path('add/', basket_add, name='basket_add'),
    path('checkout/', checkout, name='checkout'),
    path('delete/',basket_delete, name='basket_delete'),
    path('update/',basket_update, name='basket_update'),

    
    
]

product/models.py
from django.db import models

product/views.py
from django.shortcuts import render,redirect,get_object_or_404
from shop.models import Category, Product


def categories(request):
      return{
         'categories': Category.objects.all()
      }


def list(request):
   products =Product.objects.all()
   context ={
      'products':products
   }
   return render(request, 'product-list.html',context)


def product_detail(request, slug):
   product=get_object_or_404(Product, slug=slug, in_stock=True)
   products =Product.objects.all()
   context ={
      'product':product,
      'products':products

   }
   return render(request, 'product-detail.html',context)


def category_list(request, category_slug=None):
   category=get_object_or_404(Category, slug=category_slug)
   products=Product.objects.filter(category=category)
   context={
      'category': category,
      'products': products
   }
   return render(request,'product-list.html',context)

product/templates/product-detail.html
{% extends 'base.html' %}
 {% load static %} 
 {{ product.name }} 
 {% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="M_Adnan">
    <title>PAVSHOP - Multipurpose eCommerce HTML5 Template</title>


</head>

<body>

    <!-- LOADER -->
    <div id="loader">
        <div class="position-center-center">
            <div class="ldr"></div>
        </div>
    </div>

    <!-- Wrap -->
    <div id="wrap">


        <!--======= SUB BANNER =========-->
        <section class="sub-bnr" data-stellar-background-ratio="0.5">
            <div class="position-center-center">
                <div class="container">
                    <h4>COMPUTER</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec faucibus maximus vehicula. Sed feugiat, tellus vel tristique posuere, diam</p>
                    <ol class="breadcrumb">
                        <li><a href="#">Home</a></li>
                        <li class="active">Data</li>
                    </ol>
                </div>
            </div>
        </section>

        <!-- Content -->
        <div id="content">

            <!-- Popular Products -->
            <section class="padding-top-100 padding-bottom-100">
                <div class="container">

                    <!-- SHOP DETAIL -->
                    <div class="shop-detail">
                        <div class="row">

                            <!-- Popular Images Slider -->
                            <div class="col-md-7">

                                <!-- Images Slider -->
                                <div class="images-slider" style="background: none;">
                                    <ul class="slides">
                                        <li data-thumb="images/large-img-1.jpg"> <img class="img-responsive" src="{{product.image.url  }}" alt="" style="    width: 85%;"> </li>

                                    </ul>
                                </div>
                            </div>

                            <!-- COntent -->
                            <div class="col-md-5">
                                <h4{{product.title}}</h4>
                                    <span class="price"><small></small>{{product.price}} $ </span> {{product.brand}} {{product.title }} </span>

                                    <!-- Sale Tags -->
                                    <!-- <div class="on-sale"> 10% <span>OFF</span> </div> -->
                                    <ul class="item-owner">
                                        <li>Author :<span> {{product.author}}</span></li>
                                        <li>Brand:<span> {{product.brand}}</span></li>
                                    </ul>

                                    <!-- Item Detail -->
                                    <p> {{product.about_desc |safe }}</p>

                                    <!-- Short By -->
                                    <div class="some-info">
                                        <ul class="row margin-top-30">
                                            <li class="col-xs-6">
                                                <div class="col-6" style="font-size:20px">
                                                    <label style="margin-right: 12px;" for="select">Qty</label>
                                                    <select id="select">
                                             <option value="1">1</option>
                                            <option value="2">2</option>
                                            <option value="3">3</option>
                                            <option value="4">4</option>
                                             </select>

                                                </div>
                                            </li>


               
     <li class="col-xs-6"> <button style="font-size: 15px;" type="button" id="add-button" value="{{product.id}}" class="btn btn-secondary btn-sm"><i style="margin-right: 7px;
        font-size: 21px;" class="fas fa-shopping-basket"></i>Add to basket</button><li>
     <li style="float:right;" class="col-xs-6"> <button style="font-size: 15px; background: white;color: #2d3a4b;border: 2px solid#2d3a4b;" type="button" id="add-button" value="{{product.id}}" class="btn btn-secondary btn-sm"><i style="    margin-right: 7px;
        font-size: 21px;" class="fa fa-heart"></i>Add to favorite</button><li>

              

                                 

                                        <!-- Social Icons -->
                                        <ul class="social_icons">
                                            <li><a href="#."><i class="icon-social-facebook"></i></a></li>
                                            <li><a href="#."><i class="icon-social-twitter"></i></a></li>
                                            <li><a href="#."><i class="icon-social-tumblr"></i></a></li>
                                            <li><a href="#."><i class="icon-social-youtube"></i></a></li>
                                            <li><a href="#."><i class="icon-social-dribbble"></i></a></li>
                                        </ul>
                                    </div>
                            </div>
                        </div>
                    </div>
                </div>





                </script>
       
        </section>

        <!-- Popular Products -->
        <section class="light-gray-bg padding-top-150 padding-bottom-150">
            <div class="container">

                <!-- Main Heading -->
                <div class="heading text-center">
                    <h4>YOU MAY LIKE IT</h4>
                    <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec faucibus maximus vehicula. 
          Sed feugiat, tellus vel tristique posuere, diam</span> </div>

                <!-- Popular Item Slide -->
                <div class="papular-block block-slide single-img-demos">
                    {% for product in products %}
                    <!-- Item -->
                    <div class="item">
                        <!-- Item img -->
                        <div class="item-img" style="height: 256px;display: flex;
                        justify-content: center;align-items: center;margin: 20px auto;"> <img class="img-1" src="{{ product.image.url  }}" alt="">
                            <!-- Overlay -->
                            <div class="overlay">
                                <div class="position-center-center">
                                    <div class="inn"><a href="{{ product.image.url  }}" data-lighter><i class="fas fa-search"></i></a>  <a href="#."><i class="fas fa-heart"></i></a></div>
                                </div>
                            </div>
                        </div>
                        <!-- Item Name -->
                        <div class="item-name"> <a href="#.">{{product.header}}</a>
                            <p>{{product.title}}</p>
                        </div>

                        <!-- Price -->
                        <span class="price"><small></small>{{product.price}} $ </span>
                    </div>

                    {% endfor %}

                </div>
            </div>
        </section>


    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script>
        $(document).on('click', '#add-button', function(e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '{% url "shop:basket_add" %}',
                data: {
                    productid: $('#add-button').val(),
                    productqty: $('#select option:selected').text(),
                    csrfmiddlewaretoken: "{{csrf_token}}",
                    action: 'post'
                },
                success: function(json) {
                    document.getElementById("basket-qty").innerHTML = json.qty
                },
                error: function(xhr, errmsg, err) {}
            });
        })
    </script>
</body>

</html>
{% endblock %}

product/templates/product-list.html
{% extends 'base.html' %}
{% load static %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="M_Adnan">
<title>PAVSHOP - Multipurpose eCommerce HTML5 Template</title>


</head>
<body>

<!-- LOADER -->
<div id="loader">
  <div class="position-center-center">
    <div class="ldr"></div>
  </div>
</div>

<!-- Wrap -->
<div id="wrap"> 
  
  <!-- header -->

  
  <!--======= SUB BANNER =========-->
  <section class="sub-bnr" data-stellar-background-ratio="0.5"  style="	background: url({% static 'images/product-bg.jpg' %})" >
    <div class="position-center-center">
      <div class="container">
        <h4>PAVSHOP PRODUCTS</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec faucibus maximus vehicula. 
          Sed feugiat, tellus vel tristique posuere, diam</p>
        <ol class="breadcrumb">
          <li><a href="#">Home</a></li>
          <li class="active">Data</li>
        </ol>
      </div>
    </div>
  </section>
  
  <!-- Content -->
  <div id="content"> 
    
    <!-- Products -->
    <section class="shop-page padding-top-100 padding-bottom-100">
      <div class="container">
        <div class="row"> 
          
          <!-- Item Content -->
          <div class="col-sm-9">
            <div class="item-display">
              <div class="row"> 
                <!-- Products Select -->
                <div class="col-xs-6">
                  <div class="pull-left"> 
                    
                    <!-- Short By -->
                    <select class="selectpicker">
                      <option>Short By</option>
                      <option>Short By</option>
                      <option>Short By</option>
                    </select>
                    <!-- Filter By -->
                    <select class="selectpicker">
                      <option>Filter By</option>
                      <option>Short By</option>
                      <option>Short By</option>
                    </select>
                    
                    <!-- GRID & LIST --> 
                    <a href="#." class="grid-style"><i class="icon-grid"></i></a> <a href="#." class="list-style"><i class="icon-list"></i></a> </div>
                </div>
             
              </div>
            </div>
            

           
            <!-- Popular Item Slide -->
            <div class="papular-block row single-img-demos"> 
     
     
              {% for product in products %}
              <!-- Item -->
              <div class="col-md-6">
                <div class="item" style="margin-bottom: 18px;"> 
                  <!-- Item img -->
                 <div class="item-img" style="height: 274px;margin: 20px auto;padding: 10px;display: flex;justify-content: center;align-items: center;"> <img class="img-1" src="{{ product.image.url  }}   " alt="" > </a> 
                    <!-- Overlay -->
                    <div class="overlay" style="height: 100%;" >
                      <div class="position-center-center">
                        <div class="inn"><a href="{{product.image.url  }}  " data-lighter><i class="fas fa-search"></i></a>  <a href="#." ><i class="fas fa-heart"></i></a></div>
                      </div>
                    </div>
                  </div>
                  <!-- Item Name -->
                <div class="item-name"> <a href="{{product.get_absolute_url}} ">{{product.header}}</a>
                    <p>{{product.title}}</p>
                  </div>
                  <!-- Price --> 
                  <span class="price"><small>{{product.price}} $ </small></span> </div>
                  <li style="text-align: center;">Author :<span> {{product.author}}</span></li>
                  <li style="text-align: center;">Brand:<span> {{product.brand}}</span></li>
              </div>
                {% endfor  %} 
            </div>
          </div>
          
          <!-- Shop SideBar -->
          <div class="col-sm-3">
            <div class="shop-sidebar"> 
              
              <!-- Category -->
      <h5 class="shop-tittle margin-bottom-30">Category</h5>
   <h5 class="shop-tittle margin-bottom-30">{{category.name|title}}</h5>
           
              <ul class="shop-cate">
                  {% for c in categories %}
             <li>
             <a href="# "> {{c.name|title}} </a>
               </li>
                 {% endfor %} 
              </ul>
           
       
              
              <!-- TAGS -->
              <h5 class="shop-tittle margin-top-60 margin-bottom-30">PAUPLAR TAGS</h5>
              <ul class="shop-tags">
        
                  {% for c in categories %}
             <li>
             <a href="#"> # {{c.name|title}} </a>
               </li>
                 {% endfor %} 
              </ul>
           

              </ul>
              
              <!-- BRAND -->
              <h5 class="shop-tittle margin-top-60 margin-bottom-30">brands</h5>
              <ul class="shop-cate">
                <li>MSI</li>
                <li>HP</li>
                <li>Acer</li>
              </ul>
              
              <!-- SIDE BACR BANER -->
              <div class="side-bnr margin-top-50"> <img class="img-responsive" src="{% static  'images/slider.jpg' %  %}" alt="">
                <div class="position-center-center"> <span class="price"><small></small> </span>
    
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    

  
</div>

</body>
</html>
{% endblock %}  