blog/urls.py
from django.urls import path

from . import views
from blog.views import BlogListView

app_name="blog"


urlpatterns = [
    path('detail/<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('', BlogListView.as_view(), name='blog_list'),
]

mydjangoproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
      
    path('jet/', include('jet.urls', 'jet')),  
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
   


    # path('checkout/', include('order.urls', namespace="checkout")),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)




from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns += i18n_patterns(
    
    path('about/',include("about.urls",namespace="about"),),
    path('',include("product.urls",namespace="product"),),
    path('',include("shop.urls",namespace="shop"),),
    path('blog/',include("blog.urls",namespace="blog"),),
    path('',include("home.urls",namespace="home"),),
    path('contact/',include("contact.urls",namespace="email"),),
    path('contact/',include("contact.urls",namespace="thanks"),),
    path('account/',include("account.urls",namespace="register"),),
    path('account/',include("account.urls",namespace="login"),),
    path('contact/', include('contact.urls', namespace="feedback")),
    path('social-auth/', include('social_django.urls', namespace="social")),


    # path('orders/', include('orders.urls', namespace='orders')),
    
)

shop/urls.py
from django.urls import path
from .views import basket_summary, checkout,basket_add,basket_delete,basket_update

app_name = 'shop'

urlpatterns = [
    path('basket/', basket_summary, name='basket_summary'),
    path('add/', basket_add, name='basket_add'),
    path('checkout/', checkout, name='checkout'),
    path('delete/',basket_delete, name='basket_delete'),
    path('update/',basket_update, name='basket_update'),

    
    
]

shop/models.py
from django.db import models
from django.urls import reverse
from account.models import User
from ckeditor.fields import RichTextField
from phonenumber_field.modelfields import PhoneNumberField

class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)

class Category(models.Model):
    name = models.CharField(max_length=255,db_index=True)
    slug=models.SlugField(max_length=255,unique=True)

    class Meta:
        verbose_name_plural='categories'

    def get_absolute_url(self):
        return reverse('product:category_list',args=[self.slug])

    def __str__ (self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_creator')
    brand=models.CharField(max_length=225,blank=True,null=True)
    author = models.CharField(max_length=255, default='admin')
    title=models.CharField(max_length=225,blank=True,null=True)
    header=models.CharField(max_length=225,blank=True,null=True)
    image=models.ImageField(upload_to='media/')
    slug=models.SlugField(max_length=225,unique=True)
    price = models.IntegerField(blank=True,null=True)
    in_stock=models.BooleanField(default=True)
    is_active=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)
    objects = models.Manager()
    products = ProductManager()
    about_desc=RichTextField(null=True, blank=True)


    class Meta:
        verbose_name_plural='Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('product:product_detail',args=[self.slug])

    def __str__(self):
        return self.title




class  Checkout(models.Model):
    user= models.ForeignKey(User, on_delete=models.CASCADE, related_name='Checkout_user')
    first_name= models.CharField(max_length=225,blank=True,null=True)
    last_name = models.CharField(max_length=225,null=True, blank=True)
    town= models.CharField(max_length=225,null=True, blank=True)
    country= models.CharField(max_length=225,null=True, blank=True)
    phone = models.CharField(max_length=225,null=True, blank=True)
    email =models.EmailField(null=False, blank=False, unique=True)
    company = models.CharField(max_length=225,blank=True,null=True)
    address = models.CharField(max_length=225,blank=True, null=True)

shop/forms.py
from django import forms
from .models import Checkout

class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Checkout
        fields = ('adress1', 'adress2', 'town', 'zip', 'phone',)
        widgets = {
            'adress1': forms.TextInput(
                attrs={'class': 'form-control form-control-md ', 'placeholder': 'House number and street name'}),
            'adress2': forms.TextInput(
                attrs={'class': 'form-control form-control-md ', 'placeholder': 'Apartment, suite, unit, etc. (optional)'}),
            'town': forms.TextInput(
                attrs={'class': 'form-control form-control-md', 'placeholder': 'Town/City'}),
            'zip': forms.TextInput(
                attrs={'class': 'form-control form-control-md', 'placeholder': 'ZIP code'}),
            'phone': forms.TextInput(
                attrs={'class': 'form-control form-control-md', 'placeholder': 'Phone Number'}),
            
        }

shop/views.py
from django.http import JsonResponse
from django.shortcuts import render,get_object_or_404
from .basket import Basket
from shop.models import *




def basket_summary(request):
    basket = Basket(request)
    return render(request, 'summary.html', {'basket': basket})



def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, qty=product_qty)

        basketqty = basket.__len__()
        response = JsonResponse({'qty': basketqty})
        return response


def basket_delete(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.delete(product=product_id)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty,'subtotal': baskettotal})
        return response


def basket_update(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        basket.update(product=product_id, qty=product_qty)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty,'subtotal': baskettotal  })
        return response




def checkout(request):

    if request.method=="POST":       
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        town = request.POST['town']
        country = request.POST['country']
        phone = request.POST['phone']
        email = request.POST['email']
        company = request.POST['company']
        address = request.POST['address']
        user = Checkout(first_name=first_name, last_name=last_name, town=town,country=country,phone=phone,email=email,company=company,address=address)
        user.save()
        alert = True
        return render(request, 'checkout.html', {'alert':alert})
    return render(request, "checkout.html")

shop/templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="M_Adnan">
<title>PAVSHOP - Multipurpose eCommerce HTML5 Template</title>



</head>
<body>

<!-- LOADER -->
<div id="loader">
  <div class="position-center-center">
    <div class="ldr"></div>
  </div>
</div>

<!-- Wrap -->
<div id="wrap"> 
  
  <!-- header -->

  
  <!--======= SUB BANNER =========-->
  <section class="sub-bnr" data-stellar-background-ratio="0.5">
    <div class="position-center-center">
      <div class="container">
        <h4>CHECKOUT</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec faucibus maximus vehicula. 
          Sed feugiat, tellus vel tristique posuere, diam</p>
        <ol class="breadcrumb">
          <li><a href="#">Home</a></li>
          <li><a href="#">SHOP</a></li>
          <li class="active">CHECKOUT</li>
        </ol>
      </div>
    </div>
  </section>
  
  <!-- Content -->
  <div id="content"> 
    
    <!--======= PAGES INNER =========-->
    <section class="chart-page padding-top-100 padding-bottom-100">
      <div class="container"> 
        
        <!-- Payments Steps -->
        <div class="shopping-cart"> 
          
          <!-- SHOPPING INFORMATION -->
          <div class="cart-ship-info">
            <div class="row"> 
              
              <!-- ESTIMATE SHIPPING & TAX -->
              <div class="col-sm-7">
                <h6>BILLING DETAILS</h6>
           
         
                <form method="post" > 
                  {% csrf_token %}      
                  {% if messageSent %}
                <p>Thank you. Your order has been received </p>
                {% endif %}
                  <ul class="row">
                    
                    <!-- Name -->
                    <li class="col-md-6">
                      <label> *FIRST NAME
                        <input type="text" name="first_name" value=""  placeholder="">
                      </label> 
                    </li>
                    <!-- LAST NAME -->
                    <li class="col-md-6">
                      <label> *LAST NAME
                        <input type="text" name="last_name" value="" placeholder="">
                      </label>
                    </li>
                    <li class="col-md-6"> 
                      <!-- COMPANY NAME -->
                      <label>COMPANY NAME
                        <input type="text" name="company" value="" placeholder="">
                      </label>
                    </li>
                    <li class="col-md-6"> 
                      <!-- ADDRESS -->
                      <label>*ADDRESS
                        <input type="text" name="address" value="" placeholder="">
                      </label>
                    </li>
                    <!-- TOWN/CITY -->
                    <li class="col-md-6">
                      <label>*TOWN/CITY
                        <input type="text" name="town" value="" placeholder="">
                      </label>
                    </li>
                    
                    <!-- COUNTRY -->
                    <li class="col-md-6">
                      <label> COUNTRY
                        <input type="text" name="country" value="" placeholder="">
                      </label>
                    </li>
                    
                    <!-- EMAIL ADDRESS -->
                    <li class="col-md-6">
                      <label> *EMAIL ADDRESS
                        <input type="text" name="email" value="" placeholder="">
                      </label>
                    </li>
                    <!-- PHONE -->
                    <li class="col-md-6">
                      <label> *PHONE
                        <input type="text" name="phone" value="" placeholder="">
                      </label>
                    </li>
                    
                    <!-- PHONE -->
                    <li class="col-md-6">
                      <button type="submit" value="submit" class="btn" id="btn_submit" onClick="proceed();">SEND Message</button>
                    </li>
                    
                    <!-- CREATE AN ACCOUNT -->
                
                  </ul>
                </form>
                
                <!-- SHIPPING info -->
               
              </div>
         
          
            </div>
          </div>
        </div>
      </div>
    </section>
    
  
 
  </div>
  
 
      

  
</div>

</body>
</html>
{% endblock %}  

shop/templates/summary.html
 {% extends 'base.html' %} 
 {% load static %} 
 {% block content %}





 <main class="pt-5">
  <div class="container">
    <h1 class="h5" style="font-size: 20px;
    text-align: center;letter-spacing: 2px;margin: 24px; ">Shopping basket</h1>
    {% for item in basket %}
    {% with product=item.product %}
    <div data-index="{{product.id}}" class="row mb-4 border product-item">
      <div class="col-md-3 col-lg-3 order-md-first bg-light">
        <img class="img-fluid mx-auto d-block" alt="Responsive image" style="width:100%;" src="{{ product.image.url }}">
      </div>
      <div class="col-md-9 col-lg-9 ps-md-3 ps-lg-9">
        <div class="row" style="display: flex; justify-content:space-between">
          <div class="col-6">
            <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-reset">
              <h1 class="h5 pt-2" style="font-size: 18px;
              font-weight: bold;"> {{ product.brand }} {{ product.title }}</h1>
            </a>
            <div class="col border-bottom">
              <div class="row p-3">
                <div class="col-6 text-end"><span class="h6 fw-bold" style="font-size: 15px;
                  margin-left: 26px;">{{ product.price }} $ </span></div>
              </div>
            </div>
            <label for="select" style="margin-top: 22px;font-size: 17px;margin-right: 12px;">Qty</label>
            <select id="select{{product.id}}">
              <option selected>
                {{item.qty}}
              </option>
              <option value="">1</option>
              <option value="">2</option>
              <option value="">3</option>
              <option value="">4</option>
            </select>
          </div>
          <div class="col-6" style="display: flex; flex-direction: column;">
            <button onClick="window.location.reload()" type="button" style="margin-bottom:8px" id="update-button" data-index="{{product.id}} "
            class="btn btn-outline-secondary btn-sm update-button">
            Update
          </button>
          <button onClick="window.location.reload()" type="button" id="delete-button" data-index="{{product.id}}"
            class="btn btn-outline-secondary btn-sm delete-button">
            Delete
          </button>
          <a href="{% url 'shop:checkout'  %}" style="text-align: center; margin-top: 20px;font-size: 17px;color: #2d3a4b;
          font-weight: bold;text-transform: uppercase;letter-spacing: 2px;cursor: pointer;"> Checkout  </a> 
          </div>
        </div>
          </div>
      
    </div>
    {% endwith %}
    {% endfor %}
   <div class="container">
    <div class="col-12 text-end">
      <div class="h6 fw-bold" style="font-size:20px">  Total : {{basket.get_total_price}} $</div>
      
                     
    </div>
   </div>
  </div>
</main>


<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>


<script>
    // Delete Item
    $(document).on('click', '.delete-button', function (e) {
      e.preventDefault();
      var prodid = $(this).data('index');
      $.ajax({
        type: 'POST',
        url: '{% url "shop:basket_delete" %}',
        data: {
          productid: $(this).data('index'),
          csrfmiddlewaretoken: "{{csrf_token}}",
          action: 'post'
        },
        success: function (json) {
          $('.product-item[data-index="' + prodid + '"]').remove();
          document.getElementById("subtotal").innerHTML = json.subtotal;
          document.getElementById("basket-qty").innerHTML = json.qty
        },
        error: function (xhr, errmsg, err) {}
      });
    })
  
    // Update Item
    $(document).on('click', '.update-button', function (e) {
      e.preventDefault();
      var prodid = $(this).data('index');
      $.ajax({
        type: 'POST',
        url: '{% url "shop:basket_update" %}',
        data: {
          productid: $(this).data('index'),
          productqty: $('#select' + prodid + ' option:selected').text(),
          csrfmiddlewaretoken: "{{csrf_token}}",
          action: 'post'
        },
        success: function (json) {
          document.getElementById("basket-qty").innerHTML = json.qty
          document.getElementById("subtotal").innerHTML = json.subtotal
        },
        error: function (xhr, errmsg, err) {}
      });
    })
  </script>
{% endblock %}